version: '2'
services:
  nodejs:
    image: node:12-alpine
    build:
      context: back/src/
    container_name: back-blood
    depends_on:
      - dbmain
    env_file:
      - back/src/.env
    ports:
      - 3000:3000
    command:  sh -c "node index"

  dbmain:
    container_name: db-blood
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_DB: main
      POSTGRES_PASSWORD: blood
    ports:
      - 54321:5432
    volumes:
      - ./data:/var/lib/postgresql/data
