version: '2'
services:
  nodejs:
    # image: node:12-alpine
    build:
      context: back/src/
      # dockerfile: ./back/src/dockerfile
    container_name: back-blood
    # volumes:
    #   - ./back/:usr/src/app/back/
    depends_on:
      - dbmain
    links:
      - dbmain
    env_file:
      - back/src/.env
    ports:
      - 3000:3000
    # command:  sh -c "./node_modules/sequelize-cli/lib/sequelize db:migrate && node index"
    networks:
      - blood_network

  dbmain:
    container_name: db-blood
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_DB: main
      POSTGRES_PASSWORD: blood
    ports:
      - 54321:5432
    volumes:
      - ./back/src/db/data:/var/lib/postgresql/data
    networks:
      - blood_network

  telegram_bot:
    container_name: telegram-blood
    # image: node:12-alpine
    build:
      context: telegramBot/
      # dockerfile: ./telegramBot
    links:
      - dbmain
    depends_on:
      - dbmain
    # volumes:
    #   - ./telegramBot/:usr/src/app/telegramBot/
    env_file:
      - telegramBot/.env
    ports:
      - 4000:4000  
    # command:  sh -c "node index"
    networks:
      - blood_network

networks:
  blood_network:
    external:
      name: blood_network_ext
